### ISSUE TITLE
Arm64 layer of the LambdaInsightsExtension

### ISSUE THREAD

**Issue by Waltu** [awslabs/serverless-plugin-lambda-insights#13]
I'm moving to use ARM64 at lambdas and hit a problem in runtime with an error message
`
EXTENSION	Name: cloudwatch_lambda_agent	State: LaunchError	Events: []	Error Type: UnknownError
RequestId: a886211c-7c56-4358-b2fa-0f642a8f78ad Error: fork/exec /opt/extensions/cloudwatch_lambda_agent: exec format error
Extension.LaunchError
`
I find this issue and looks like ARM has a own layer a bit different naming convention
Arm64
arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension-Arm64:1
Current
arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension:14

A related issue can be found from here
https://github.com/aws-samples/aws-lambda-extensions/issues/57#issuecomment-972760316

I was thinking to add a new boolean attribute to config like `arm64: true`

**Comment by Waltu** [comment]
I'm happy to provide PR if we are okay with this additional property to configuration. Another possible solution could be that we can check from the `architecture` field from serverless.yaml file and resolve the right extension based on that

**Comment by iriskraja77** [comment]
Hi @Waltu thanks for coming here with this issue. Feel free to open a PR, I would prefer the second option, to make it more seamless.  Thanks!

**Comment by mwarkentin** [comment]
@iriskraja77 @Waltu looks like this was opened in #14 - any idea if someone is going to be reviewing that PR?
