### ISSUE TITLE
SyntaxError: Unexpected token '?'  if ((architecture ?? this.provider.architecture) === 'arm64') {

### ISSUE THREAD

**Issue by bissli82** [awslabs/serverless-plugin-lambda-insights#15]
While using the plugin under serverless2.0 with Nodejs 12.x I'm getting the bellow error,
I think it's since "nullish coalescing operator"(??) isn't supported on lower versions of nodejs (only 14.5 and above - with ECMAScript11+)

Syntax Error -------------------------------------------
 
  SyntaxError: Unexpected token '?'
  /opt/atlassian/pipelines/agent/build/node_modules/serverless-plugin-lambda-insights/index.js:98
          if ((architecture ?? this.provider.architecture) === 'arm64') {
                             ^
  
  SyntaxError: Unexpected token '?'

**Comment by iriskraja77** [comment]
Thank you for reporting the issue, working on a fix today.
