### ISSUE TITLE
Configuration schema extension does not pass `strict` validation mode

### ISSUE THREAD

**Issue by pgrzesik** [awslabs/serverless-plugin-lambda-insights#17]
Hello,

along with the upcoming `v3` release of the Serverless Framework, internal schema validation has been improved and now enforces `strict` validation mode. Unfortunately, after preliminary tests, it seems like the schema extension implemented in this plugin does not adhere to strict validation rules and needs to be adjusted in order to support `v3` release of the Framework. The best way to verify that is to use the plugin along with the latest `v3` prerelease (or official release soon). 

I'm happy to answer any additional questions.

**Comment by ysle** [comment]
yup, it's like : 

```s
Running "serverless" from node_modules
Environment: win32, node 17.3.0, framework 3.0.0 (local) 3.0.0v (global), plugin 6.0.0, SDK 4.3.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: strict mode: unknown keyword: "defaultLambdaInsights" 
```

**Comment by pgrzesik** [comment]
@ysle There's a pending PR that will address this, but so far it didn't get any attention from the maintainers of this repo - we will need to wait a little bit.

**Comment by iriskraja77** [comment]
[PR](https://github.com/awslabs/serverless-plugin-lambda-insights/pull/18) is merged, thank you for the contribution and raising the issue.

**Comment by pgrzesik** [comment]
Thanks a lot @iriskraja77 🙇
