### ISSUE TITLE
support multiple function

### ISSUE THREAD

**Issue by coderhglee** [awslabs/serverless-plugin-lambda-insights#24]
## Description
When multiple serverless functions are declared, insight layer is not created from next function when a function that does disabled lambdaInsights is included

```
      functions: {
        myFunction: {
          lambdaInsights: false,
          handler: 'handler.hello',
        },
        myFunction2: {
          lambdaInsights: true,
          handler: 'handler.hello',
        },
      },
```

myFunction2.layers is not defined `LambdaInsightsExtension`

## Proposed change

https://github.com/awslabs/serverless-plugin-lambda-insights/blob/15521fcd9179b79170591b1701e6b753b38a59e7/index.js#L161

use `continue;` instead of `return;`

**Comment by iriskraja77** [comment]
Thanks @coderhglee the issue is now fixed.

**Comment by coderhglee** [comment]
Thanks a lot @iriskraja77
