### ISSUE TITLE
Update layer versions to latest available

### ISSUE THREAD

**Issue by corey-cole** [awslabs/serverless-plugin-lambda-insights#34]
Update x86_64 layer version ARNs to the latest values published in the Lambda Insights documentation:  https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versionsx86-64.html

**Comment by iriskraja77** [comment]
Thanks! Updates done in https://github.com/awslabs/serverless-plugin-lambda-insights/pull/38 so closing this issue.
