### ISSUE TITLE
Add cost estimates to readme

### ISSUE THREAD

**Issue by Lusitaniae** [awslabs/serverless-plugin-lambda-insights#37]
I've been running this plugin on my code base for awhile but now that we're down scaling development and cutting costs aggressively we will be looking into reducing or removing most of this plugin usage.

Example, if this plugin adds in average 1$ per function:
10 services
x 20 function each
x 3 environments (dev,stage,prod)
x 10$
= 600$ per month

But I think would be useful to document an estimate of costs generated by this plugin (instead of my made up numbers)

In some services we could consider using if else plugin to enable this plugin more selectively (i.e. only production)

**Comment by iriskraja77** [comment]
Thanks for opening this issue @Lusitaniae 

Pricing information for Lambda Insights is publicly available in AWS Docs [Using Lambda Insights. ](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights.html).
