### ISSUE TITLE
Error: Unknown latest version for region 'sa-east-1'. Check the Lambda Insights documentation to get the list of currently supported versions.

### ISSUE THREAD

**Issue by wbruno** [awslabs/serverless-plugin-lambda-insights#39]
I'm trying to use `lambda-insights` in `sa-east-1` with `architecture: arm64`, but even with this plugin on version 2.0.0, I'm seeing this error:

>  Error: Unknown latest version for region 'sa-east-1'. Check the Lambda Insights documentation to get the list of currently supported versions.

**Comment by iriskraja77** [comment]
Hi @wbruno 

Here is a list of supported Lambda Insights extension for ARM64 platforms: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versionsARM.html . The region you're trying to use is not supported for Lambda Insights _arm64_ platforms.
