### ISSUE TITLE
Clarity on 2.0.0

### ISSUE THREAD

**Issue by emilio-martinez** [awslabs/serverless-plugin-lambda-insights#42]
Hello 👋 just wanted to drop a quick note to ask what the breaking changes are for the 2.0.0 release. I realize issues are not really meant for this, but couldn't find a tag or release notes.

Much appreciated!

**Comment by Lucaslgf2** [comment]
Hello, I would also like to know the same thing and I couldn't find it anywhere.

**Comment by iriskraja77** [comment]
Thank you for raising this and I've added a Changelog file we'll keep up to date for future releases. 

The main change is related to https://github.com/awslabs/serverless-plugin-lambda-insights/pull/31 and how the wrong Lambda Insights layer is used if the global provider architecture is different than the function level layer version. The deployment in CloudFormation succeeded with the wrong layer version before that PR was merged.
